[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$selected=@('Military_Tool_Kit','U.S.M113_APC_by_Papa_Chad','VehicleRepairOverhaul','VehicleSalvageOverhaulB42',
    'GydeTraitMags','82porsche911','B42_PZLinux','KATTAJ1_ClothesCore','KATTAJ1_Military','CerberusPack',
    '[MT] Nano Armor - Easy','LBB42','U.S. M998 Humvee by Papa_Chad','LNB42',
    'U.S. M163 VADS by Papa_Chad by Papa_Chad','LKB42','84corvette','NVFramework','78lamboCountach',
    'LTWB42','bdtmre','RepairAnyWeapons','Metro2033Armory','dk_gunrepairkit')
$builds=Import-Csv (Join-Path $root 'research/mod-builds.csv') | Where-Object {$_.ModId -in $selected}
if (@($builds).Count -ne $selected.Count) {throw 'Selected mod IDs are missing from the audited build inventory.'}
$builds | Select-Object WorkshopId,ModId,Version,Requires | ConvertTo-Json -Depth 4 |
    Set-Content (Join-Path $root 'config/knights-selected-mods.json') -Encoding utf8
$gear=@('Military_Tool_Kit','GydeTraitMags','KATTAJ1_ClothesCore','KATTAJ1_Military','CerberusPack',
    '[MT] Nano Armor - Easy','LBB42','LNB42','LKB42','LTWB42','bdtmre','Metro2033Armory','dk_gunrepairkit')
$vehicleMods=@('U.S.M113_APC_by_Papa_Chad','82porsche911','U.S. M998 Humvee by Papa_Chad',
    'U.S. M163 VADS by Papa_Chad by Papa_Chad','84corvette','78lamboCountach')
$rows=@(Import-Csv (Join-Path $root 'research/script-declarations.csv') | Where-Object {$_.ModId -in $selected})
function Get-Block($row) {
    $body=[IO.File]::ReadAllText($row.File)
    $name=($row.Id -split '\.')[-1]
    $m=[regex]::Match($body,'(?m)^\s*'+$row.Kind+'\s+'+[regex]::Escape($name)+'\s*\{')
    if (!$m.Success) {throw "Unable to parse declaration $($row.Id)"}
    $start=$body.IndexOf('{',$m.Index); $depth=1; $end=$start+1
    while ($depth -gt 0 -and $end -lt $body.Length) {
        if ($body[$end] -eq '{') {$depth++} elseif ($body[$end] -eq '}') {$depth--}; $end++
    }
    return $body.Substring($start,$end-$start)
}
$items=@($rows | Where-Object {$_.Kind -eq 'item' -and ($_.ModId -in $gear -or $_.ModId -in $vehicleMods)} | Sort-Object Id -Unique)
$recipes=@($rows | Where-Object {$_.Kind -in 'craftRecipe','recipe' -and $_.ModId -in $gear -and $_.Id -notmatch '(?i)repair|refill|recharge|reload|unload|load|paint|attach|detach'} | Sort-Object Id -Unique)
$catalog=@()
foreach($row in $items) {
    $block=Get-Block $row
    $type=[regex]::Match($block,'(?im)^\s*(?:ItemType|Type)\s*=\s*([^,\r\n]+)').Groups[1].Value.Trim()
    if ($row.ModId -in $vehicleMods -and $row.Id -notmatch '(?i)Vulcan|20mm|Browning|M22') {continue}
    if ($row.ModId -eq 'bdtmre' -and ($type -notmatch '(?i)food$' -or $row.Id -match '(?i)box|case|old|legacy')) {continue}
    if ($row.ModId -eq 'Military_Tool_Kit' -and $row.Id -notmatch '^Base\.(20x102|127x99|M61_Vulcan|Browning_M22)') {continue}
    if ($row.Id -match '(?i)empty|handmade|blade$|handle$|case$') {continue}
    $price=1000
    if ($type -match 'Clothing') {$price=7500}
    if ($type -match 'Weapon' -and $type -notmatch 'Part') {$price=35000}
    if ($type -match 'Container') {$price=18000}
    if ($row.Id -match '(?i)mag|sheath|holster|strap|mount') {$price=1500}
    if ($row.Id -match '(?i)round|bullet|ammo|bearing') {$price=100}
    if ($row.Id -match '(?i)box') {$price=2500}
    if ($row.ModId -eq 'GydeTraitMags') {$price=30000}
    if ($row.ModId -eq '[MT] Nano Armor - Easy') {$price=20000}
    if ($row.ModId -eq 'bdtmre') {$price=350}
    if ($row.Id -eq 'GunRepairKit.GunRepairKit') {$price=750}
    if ($row.Id -eq 'GunRepairKit.GunRepairKitAdvanced') {$price=2500}
    if ($row.ModId -eq 'dk_gunrepairkit' -and $row.Id -notmatch 'GunRepairKit(?:Advanced)?$') {continue}
    $catalog += [ordered]@{id=$row.Id;price=$price;mod=$row.ModId;type=$type}
}
$vehicles=@($rows | Where-Object {$_.Kind -eq 'vehicle'} | Sort-Object Id -Unique)
$cars=@()
foreach($row in $vehicles) {
    if ($row.ModId -eq 'U.S.M113_APC_by_Papa_Chad') {continue}
    $price=325000
    if ($row.Id -eq 'Base.M998_Humvee') {$price=350000}
    if ($row.Id -eq 'Base.M163') {$price=1000000}
    $cars += [ordered]@{id=$row.Id;price=$price;mod=$row.ModId}
}
$pricePath=Join-Path $root 'config/knights-reward-prices.json'
if (Test-Path $pricePath) {
    $previous=Get-Content $pricePath -Raw | ConvertFrom-Json
    $prices=@{}; foreach($entry in @($previous.items)+@($previous.vehicles)) {$prices[$entry.id]=$entry.price}
    foreach($entry in @($catalog)+@($cars)) {if($prices.ContainsKey($entry.id)) {$entry.price=$prices[$entry.id]}}
}
[ordered]@{version=1;note='Editable initial reference prices; PZLinux retains skill and reputation pricing. No world-age inflation.';items=$catalog;vehicles=$cars} |
    ConvertTo-Json -Depth 8 | Set-Content $pricePath -Encoding utf8
$lines=[Collections.Generic.List[string]]::new()
$lines.Add('-- Generated by build-reward-catalog.ps1 from audited Workshop declarations and editable price configuration.')
$lines.Add('require "KnightsDan/Core"')
$lines.Add('KnightsDan.rewardItems = {')
foreach($row in $items) {$lines.Add('    ["'+$row.Id+'"] = true,')}
$lines.Add('}'); $lines.Add('KnightsDan.rewardVehicles = {')
foreach($row in $vehicles) {$lines.Add('    ["'+$row.Id+'"] = true,')}
$lines.Add('}'); $lines.Add('KnightsDan.blockedRecipes = {')
foreach($row in $recipes) {$lines.Add('    ["'+$row.Id+'"] = true,')}
$lines.Add('}'); $lines.Add('KnightsDan.shopItems = {')
foreach($entry in $catalog) {$lines.Add('    {id="'+$entry.id+'", price='+$entry.price+'},')}
$lines.Add('}'); $lines.Add('KnightsDan.shopVehicles = {')
foreach($entry in $cars) {$lines.Add('    {id="'+$entry.id+'", price='+$entry.price+'},')}
$lines.Add('}')
$destination=Join-Path $root 'custom-mods/KnightsDanServerPatch/42/media/lua/shared/KnightsDan/Catalog.lua'
[IO.File]::WriteAllLines($destination,$lines,[Text.UTF8Encoding]::new($false))
$disabled=[Collections.Generic.List[string]]::new()
$disabled.Add('// Reward-only manufacturing recipes are disabled by the B42 script loader.')
foreach($group in ($recipes | Where-Object {$_.Kind -eq 'craftRecipe'} | Group-Object File)) {
    $source=[IO.File]::ReadAllText($group.Name).TrimStart([char]0xFEFF)
    $module=[regex]::Match($source,'(?m)^\s*module\s+([\w.]+)').Groups[1].Value
    if(!$module){throw 'Missing recipe module.'}
    $disabled.Add('module '+$module+' {')
    foreach($recipe in $group.Group){$disabled.Add('    craftRecipe '+$recipe.Id+' { enabled = false, }')}
    $disabled.Add('}')
}
$disabledPath=Join-Path $root 'custom-mods/KnightsDanServerPatch/42/media/scripts/KnightsDanDisabledRecipes.txt'
[IO.File]::WriteAllLines($disabledPath,$disabled,[Text.UTF8Encoding]::new($false))
Write-Output ('Catalog: {0} shop items, {1} cars; restrictions: {2} items, {3} vehicles, {4} creation recipes' -f $catalog.Count,$cars.Count,$items.Count,$vehicles.Count,$recipes.Count)
